import { Link, useLocation, useNavigate } from "react-router-dom";
import type { LocaleCode } from "../locales/appContent";

const PRIVACY_COPY: Record<LocaleCode, {
    badge: string;
    title: string;
    subtitle: string;
    updatedLabel: string;
    languageLabel: string;
    backLabel: string;
    contactIntro: string;
    contactEmail: string;
    sections: { title: string; body: string[] }[];
}> = {
    en: {
        badge: "Privacy & Policy",
        title: "How this portfolio handles your data",
        subtitle: "This notice explains, in plain terms, how personal data is handled across the portfolio.",
        updatedLabel: "Last updated: January 19, 2026",
        languageLabel: "Language",
        backLabel: "← Back to portfolio",
        contactIntro: "For any questions regarding this policy you can reach me at",
        contactEmail: "nico.maffioli@gmail.com",
        sections: [
            {
                title: "Data Controller",
                body: [
                    "This website is operated by Niccolò Maffioli.",
                    "For any privacy-related request you can contact me at nico.maffioli@gmail.com.",
                ],
            },
            {
                title: "Types of data processed",
                body: [
                    "This portfolio does not require accounts, registrations, or payments and it does not automatically collect personal data.",
                    "Personal data (such as name, email address, or message content) is processed only if you voluntarily contact me via email, LinkedIn, or other channels listed on the website.",
                ],
            },
            {
                title: "Purpose and legal basis of processing",
                body: [
                    "Personal data voluntarily provided is processed solely to respond to contact or information requests and to initiate potential professional communications.",
                    "Legal basis: performance of pre-contractual measures requested by the data subject (Art. 6(1)(b) GDPR) and the legitimate interest of the data controller in replying to incoming communications (Art. 6(1)(f) GDPR).",
                ],
            },
            {
                title: "Processing methods",
                body: [
                    "Data is processed lawfully, fairly, and transparently, mainly through electronic tools and with appropriate security measures in place.",
                ],
            },
            {
                title: "Data retention",
                body: [
                    "Personal data is retained only for the time strictly necessary to handle and respond to the request, after which it is deleted unless retention is required by law or further communication is agreed upon with the data subject.",
                ],
            },
            {
                title: "Cookies and similar technologies",
                body: [
                    "This website does not use marketing or tracking cookies.",
                ],
            },
            {
                title: "Local Storage",
                body: [
                    "A single localStorage key (terminal-onboarding) stores whether the introductory tour has been dismissed:",
                    "- it remains entirely within the user's browser;",
                    "- it is not transmitted to external servers;",
                    "- it can be cleared at any time through the browser settings.",
                ],
            },
            {
                title: "Analytics",
                body: [
                    "No analytics tools are currently in use. Users are not profiled and browsing is not monitored, apart from minimal technical logs generated by the hosting provider for security and maintenance purposes.",
                ],
            },
            {
                title: "User accounts and payments",
                body: [
                    "The website does not include registration or authentication systems, restricted areas, payment checkouts, subscriptions, or donation features; consequently, no payment data is collected or processed.",
                ],
            },
            {
                title: "Data sharing and transfers",
                body: [
                    "Personal data is not shared with third parties.",
                    "Standard infrastructure providers (hosting, CDN) may process data solely to guarantee the technical operation of the site and are bound by their own confidentiality policies.",
                    "Personal data is not transferred outside the European Union.",
                ],
            },
            {
                title: "Data subject rights",
                body: [
                    "Under Regulation (EU) 2016/679 you have the right to access your personal data, request rectification or updates, erasure, restriction of processing, object to processing, and request data portability (where applicable).",
                    "Requests can be sent to nico.maffioli@gmail.com.",
                    "You also have the right to lodge a complaint with the Italian Data Protection Authority (Garante per la Protezione dei Dati Personali).",
                ],
            },
            {
                title: "Policy updates",
                body: [
                    "This policy may be updated if new features are introduced (for example analytics tools or personal areas).",
                    "Any significant change will be published on this page together with the new revision date.",
                ],
            },
        ],
    },
    it: {
        badge: "Privacy & Policy",
        title: "Come tratto i tuoi dati",
        subtitle: "Questa informativa descrive in modo trasparente come gestisco i dati personali raccolti tramite il portfolio.",
        updatedLabel: "Ultimo aggiornamento: 19 gennaio 2026",
        languageLabel: "Lingua",
        backLabel: "← Torna al portfolio",
        contactIntro: "Per qualsiasi domanda su questa informativa puoi scrivermi a",
        contactEmail: "nico.maffioli@gmail.com",
        sections: [
            {
                title: "Titolare del trattamento",
                body: [
                    "Questo sito è gestito da Niccolò Maffioli.",
                    "Per qualsiasi richiesta relativa alla privacy o al trattamento dei dati personali puoi contattarmi all'indirizzo email: nico.maffioli@gmail.com.",
                ],
            },
            {
                title: "Tipologia di dati trattati",
                body: [
                    "Il portfolio non richiede account, registrazioni né pagamenti e non raccoglie automaticamente dati personali.",
                    "Eventuali dati personali (come nome, indirizzo email o contenuto del messaggio) vengono trattati solo se scegli volontariamente di contattarmi tramite email, LinkedIn o altri canali indicati nel sito.",
                ],
            },
            {
                title: "Finalità e base giuridica del trattamento",
                body: [
                    "I dati personali forniti volontariamente vengono trattati esclusivamente per rispondere a richieste di contatto o informazioni e per avviare eventuali comunicazioni professionali.",
                    "Base giuridica del trattamento:",
                    "- esecuzione di misure precontrattuali richieste dall'interessato (art. 6.1.b GDPR);",
                    "- legittimo interesse del titolare a rispondere alle comunicazioni ricevute (art. 6.1.f GDPR).",
                ],
            },
            {
                title: "Modalità del trattamento",
                body: [
                    "Il trattamento avviene in modo lecito, corretto e trasparente, prevalentemente tramite strumenti elettronici e nel rispetto di misure di sicurezza adeguate.",
                ],
            },
            {
                title: "Conservazione dei dati",
                body: [
                    "I dati personali vengono conservati per il tempo strettamente necessario a gestire e rispondere alla richiesta e successivamente cancellati, salvo obblighi di legge o eventuali comunicazioni ulteriori concordate con l'interessato.",
                ],
            },
            {
                title: "Cookie e tecnologie simili",
                body: [
                    "Il sito non utilizza cookie di profilazione o marketing.",
                ],
            },
            {
                title: "Local Storage",
                body: [
                    "Viene utilizzata una sola chiave di localStorage (terminal-onboarding) per ricordare se il tour introduttivo è già stato visualizzato:",
                    "- resta esclusivamente nel browser dell'utente;",
                    "- non viene trasmessa a server esterni;",
                    "- può essere eliminata in qualunque momento tramite le impostazioni del browser.",
                ],
            },
            {
                title: "Analytics",
                body: [
                    "Al momento non vengono utilizzati strumenti di analytics. Non effettuo profilazione degli utenti né monitoraggio della navigazione oltre agli eventuali log tecnici minimi generati dal provider di hosting per motivi di sicurezza e manutenzione.",
                ],
            },
            {
                title: "Account, aree riservate e pagamenti",
                body: [
                    "Il sito non prevede sistemi di registrazione o autenticazione, aree riservate né funzioni di pagamento, checkout, abbonamenti o donazioni; di conseguenza non vengono raccolti dati di pagamento.",
                ],
            },
            {
                title: "Comunicazione e trasferimento dei dati",
                body: [
                    "I dati personali non vengono condivisi con terze parti.",
                    "Eventuali fornitori infrastrutturali (hosting, CDN) trattano i dati esclusivamente per garantire il funzionamento tecnico del sito e sono vincolati alle rispettive policy di riservatezza.",
                    "I dati non vengono trasferiti al di fuori dell'Unione Europea.",
                ],
            },
            {
                title: "Diritti dell'interessato",
                body: [
                    "Ai sensi del Regolamento (UE) 2016/679 hai il diritto di accedere ai tuoi dati personali, richiederne la rettifica o l'aggiornamento, la cancellazione, la limitazione del trattamento, opporti al trattamento e richiedere la portabilità dei dati (ove applicabile).",
                    "Le richieste possono essere inviate a nico.maffioli@gmail.com.",
                    "Hai inoltre il diritto di proporre reclamo al Garante per la Protezione dei Dati Personali.",
                ],
            },
            {
                title: "Aggiornamenti dell'informativa",
                body: [
                    "Questa informativa potrà essere aggiornata in caso di modifiche o introduzione di nuove funzionalità (ad esempio strumenti di analytics o aree personali).",
                    "Ogni aggiornamento rilevante verrà pubblicato in questa pagina con l'indicazione della nuova data di revisione.",
                ],
            },
        ],
    },
};

const PrivacyPolicy = () => {
    const location = useLocation();
    const navigate = useNavigate();
    const params = new URLSearchParams(location.search);
    const langParam = params.get("lang") === "it" ? "it" : "en";
    const copy = PRIVACY_COPY[langParam];

    const handleLanguageChange = (lang: LocaleCode) => {
        if (lang === langParam) return;
        const next = new URLSearchParams(location.search);
        if (lang === "en") {
            next.delete("lang");
        } else {
            next.set("lang", lang);
        }
        navigate({
            pathname: location.pathname,
            search: next.toString() ? `?${next.toString()}` : "",
        }, { replace: true });
    };

    return (
        <div className="min-h-screen bg-terminal-bg text-terminal-fg px-4 py-10 sm:px-8">
            <div className="mx-auto w-full max-w-3xl space-y-8 text-sm leading-relaxed sm:text-base">
                <div className="flex flex-wrap items-center justify-between gap-4 text-[10px] uppercase tracking-[0.3em] text-terminal-fg/60">
                    <Link
                        to="/"
                        className="inline-flex items-center gap-1 text-terminal-cyan/80 transition-colors hover:text-terminal-cyan"
                    >
                        {copy.backLabel}
                    </Link>
                    <div className="flex items-center gap-2">
                        <span className="text-terminal-fg/40">{copy.languageLabel}</span>
                        {["en", "it"].map((lang) => (
                            <button
                                key={lang}
                                type="button"
                                onClick={() => handleLanguageChange(lang as LocaleCode)}
                                className={`rounded-full border px-3 py-1 font-semibold tracking-[0.3em] transition-colors ${langParam === lang
                                    ? "border-terminal-cyan/70 bg-terminal-cyan/90 text-terminal-bg"
                                    : "border-terminal-fg/20 text-terminal-fg/60 hover:text-terminal-cyan"
                                    }`}
                                aria-pressed={langParam === lang}
                            >
                                {lang.toUpperCase()}
                            </button>
                        ))}
                    </div>
                </div>

                <header className="space-y-4">
                    <p className="text-xs uppercase tracking-[0.35em] text-terminal-cyan/70">{copy.badge}</p>
                    <h1 className="text-3xl font-semibold text-terminal-cyan">{copy.title}</h1>
                    <p className="text-terminal-fg/70">{copy.subtitle}</p>
                    <p className="text-terminal-fg/50">{copy.updatedLabel}</p>
                </header>

                {copy.sections.map((section) => (
                    <section key={section.title} className="space-y-2">
                        <h2 className="text-lg font-semibold text-terminal-cyan">{section.title}</h2>
                        {section.body.map((paragraph, paragraphIndex) => (
                            <p key={`${section.title}-${paragraphIndex}`}>{paragraph}</p>
                        ))}
                    </section>
                ))}

                <div className="border-t border-terminal-fg/20 pt-6 text-sm text-terminal-fg/80">
                    <p>
                        {copy.contactIntro}
                        <a
                            href={`mailto:${copy.contactEmail}`}
                            className="ml-1 text-terminal-cyan underline-offset-4 hover:underline"
                        >
                            {copy.contactEmail}
                        </a>
                        .
                    </p>
                    <Link
                        to="/"
                        className="mt-4 inline-flex items-center text-terminal-cyan/80 underline-offset-4 hover:underline"
                    >
                        {copy.backLabel}
                    </Link>
                </div>
            </div>
        </div>
    );
};

export default PrivacyPolicy;
